version: '3'


services:
  paciente:
    build: ./Microservice/paciente-service
    depends_on:
      - mongo
    environment:
      - PORT=4000
      - MONGODB_CNN=mongodb://mongo:27017/paciente
  tipoexamen:
    build: ./Microservice/tipoExamen-service
    depends_on:
      - mongo
    environment:
      - PORT=4000
      - MONGODB_CNN=mongodb://mongo:27017/tipoexamen

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - paciente
      - tipoexamen

  mongo:
    image: mongo
    ports:
      - "27017:27017"
